import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{motion,useReducedMotion}from'framer-motion';import{ArrowRight,Menu,X,ChevronDown,MessageCircle,Workflow,BrainCircuit,MousePointer2,GitBranch,ChartNoAxesCombined,Check}from'lucide-react';import'./index.css';
const WA='https://wa.me/5587988195026';
const nav=[['Revenue OS','revenue-os'],['Raio-X','raio-x'],['Soluções','solucoes'],['Cases','provas'],['Contato','contato']];
function Logo(){return <a className="logo" href="#top" aria-label="7UP"><b>7</b>UP</a>}
function Btn({children,secondary=false,href=WA}:{children:React.ReactNode;secondary?:boolean;href?:string}){return <a className={'btn '+(secondary?'secondary':'')} href={href} target={href.startsWith('http')?'_blank':undefined} rel={href.startsWith('http')?'noopener noreferrer':undefined}>{children}<ArrowRight size={16}/></a>}
function Reveal({children,delay=0}:{children:React.ReactNode;delay?:number}){const r=useReducedMotion();return <motion.div initial={r?false:{opacity:0,y:24}} whileInView={r?undefined:{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.65,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}
function Header(){const[o,setO]=useState(false);return <header><div className="nav wrap"><Logo/><nav>{nav.map(([x,id])=><a key={id} href={'#'+id}>{x}</a>)}</nav><a className="navbtn" href={WA} target="_blank" rel="noopener noreferrer">DIAGNOSTICAR <ArrowRight size={14}/></a><button className="menub" onClick={()=>setO(!o)} aria-label="Menu">{o?<X/>:<Menu/>}</button></div>{o&&<div className="mobile">{nav.map(([x,id])=><a key={id} href={'#'+id} onClick={()=>setO(false)}>{x}</a>)}<a href={WA} target="_blank" rel="noopener noreferrer">DIAGNOSTICAR MINHA OPERAÇÃO</a></div>}</header>}
function Flow(){let ns=['ATENÇÃO','LEAD','QUALIFICAÇÃO','VENDA','RECEITA'];return <div className="flow"><div className="ring r1"/><div className="ring r2"/><div className="flowgrid"/><div className="flowcore"><small>7UP REVENUE FLOW</small><strong>Revenue<br/><i>OS</i></strong></div>{ns.map((n,i)=><motion.div className={'node n'+i} key={n} animate={{y:[0,-5,0]}} transition={{duration:3,delay:i*.2,repeat:Infinity}}><span/> {n}</motion.div>)}</div>}
function Label({n,t}:{n:string;t:string}){return <div className="label"><b>{n}</b><i/>{t}</div>}
function Hero(){return <section className="hero" id="top"><div className="hero-grid wrap"><Reveal><div className="eyebrow">● 7UP — ENGENHARIA DE RECEITA & GROWTH</div><h1>Transformamos <em>marketing, vendas e tecnologia</em> em uma operação previsível de receita.</h1><p>A 7UP estrutura aquisição, qualificação, vendas, CRM e automação em um único sistema para empresas que querem crescer com mais previsibilidade — e menos achismo.</p><div className="actions"><Btn>QUERO DIAGNOSTICAR MINHA OPERAÇÃO</Btn><Btn href="#revenue-os" secondary>CONHECER A 7UP</Btn></div></Reveal><Reveal delay={.1}><Flow/></Reveal></div></section>}
function Break(){let a=['TRÁFEGO','LEAD','ATENDIMENTO','QUALIFICAÇÃO','PROPOSTA','FOLLOW-UP','VENDA','RECEITA'];return <section className="dark sec"><div className="wrap"><Reveal><Label n="01" t="A quebra de crença"/><h2>Seu problema pode não ser<br/><span>falta de leads.</span></h2><p className="lead">Pode ser o que acontece <b>depois que eles chegam.</b></p></Reveal><Reveal><div className="journey">{a.map((x,i)=><div key={x} className={[2,3,5].includes(i)?'tension':''}><small>0{i+1}</small><b>{x}</b></div>)}</div><div className="tags">Resposta lenta · Lead sem qualificação · Follow-up perdido · CRM sem processo · Marketing desconectado do comercial</div></Reveal></div></section>}
function Position(){return <section className="sec pale"><div className="wrap"><Reveal><Label n="02" t="Novo modelo"/><h2>Empresas que querem crescer<br/>não precisam de <span>mais uma agência.</span></h2><p className="lead">Precisam de uma <b>operação de receita.</b></p></Reveal><div className="versus"><div className="model"><small>AGÊNCIA TRADICIONAL</small><strong>Marketing</strong><i>↓</i><strong>Leads</strong><i>↓</i><strong>Entrega</strong></div><b className="vs">VERSUS</b><div className="model new"><small>7UP</small><strong>Marketing + Vendas + Tecnologia</strong><i>↓</i><strong>Receita</strong></div></div></div></section>}
const mods=[['01','AQUISIÇÃO','Atrair a demanda certa.',MousePointer2],['02','CONVERSÃO','Transformar atenção em oportunidade.',Workflow],['03','QUALIFICAÇÃO','Separar intenção de ruído.',GitBranch],['04','VENDAS','Construir processo para converter.',ChartNoAxesCombined],['05','INTELIGÊNCIA','Decidir com dados, não achismo.',BrainCircuit]] as const;
function OS(){return <section className="sec" id="revenue-os"><div className="wrap"><Reveal><Label n="03" t="O sistema"/><div className="oshead"><div><h2>7UP <span>REVENUE OS</span></h2><p>Um sistema que conecta marketing, vendas e tecnologia em uma única operação de crescimento.</p></div><strong>7UP<span>OS</span></strong></div></Reveal><div className="rows">{mods.map(([n,t,d,I],i)=>{let Icon=I;return <Reveal key={t} delay={i*.05}><div className="row"><small>{n}</small><Icon/><b>{t}</b><span>{d}</span><ArrowRight/></div></Reveal>})}</div></div></section>}
function Xray(){let a=['AQUISIÇÃO','LEADS','ATENDIMENTO','QUALIFICAÇÃO','PROPOSTA','FOLLOW-UP','VENDA'];return <section className="sec pale" id="raio-x"><div className="wrap two"><Reveal><Label n="04" t="Diagnóstico"/><h2>Antes de escalar,<br/><span>descubra onde sua receita está vazando.</span></h2><p>O Raio-X da Receita identifica gargalos entre aquisição, atendimento, vendas e receita para mostrar onde sua operação está perdendo oportunidades.</p><Btn>QUERO FAZER O RAIO-X</Btn></Reveal><Reveal><div className="xray">{a.map((x,i)=><div key={x}><small>0{i+1}</small><b>{x}</b><span>{i===a.length-1?'●':'↓'}</span></div>)}</div></Reveal></div></section>}
function Process(){let a=['DIAGNOSTICAR','IMPLEMENTAR','MEDIR','OTIMIZAR','ESCALAR','DIAGNOSTICAR NOVAMENTE'];return <section className="sec"><div className="wrap"><Reveal><Label n="05" t="Ciclo operacional"/><h2>Não é uma campanha.<br/><span>É um ciclo de melhoria.</span></h2></Reveal><div className="timeline">{a.map((x,i)=><div key={x}><small>0{i+1}</small><b>{x}</b></div>)}</div></div></section>}
const sols=['Aquisição','Landing Pages','Conversão','CRM','Automação','SDR com IA','Processos Comerciais','Dashboards','Revenue Operations'];
function Solutions(){return <section className="sec dark" id="solucoes"><div className="wrap"><Reveal><Label n="06" t="As alavancas"/><div className="two title2"><h2>Um sistema.<br/><span>Várias alavancas.</span></h2><p>Cada elemento existe para fortalecer o mesmo objetivo: transformar demanda em receita.</p></div></Reveal><div className="solmap"><div className="center"><Logo/><small>REVENUE OS</small></div>{sols.map((x,i)=><span key={x} style={{'--i':i} as React.CSSProperties}>{x}</span>)}</div></div></section>}
function Fit(){let a=['Empresas com operação comercial.','Empresas que já investem em aquisição.','Empresas que querem previsibilidade.','Empresas que precisam integrar marketing e vendas.','Empresas que querem tomar decisões baseadas em dados.'];return <section className="sec pale"><div className="wrap two"><Reveal><Label n="07" t="Fit"/><h2>A 7UP é para empresas que <span>já estão em movimento.</span></h2></Reveal><Reveal><div className="fit">{a.map((x,i)=><div key={x}><Check/><span>{x}</span><small>0{i+1}</small></div>)}</div></Reveal></div></section>}
function Proof(){return <section className="sec" id="provas"><div className="wrap"><Reveal><Label n="08" t="Prova"/><h2>Quando marketing deixa de ser despesa<br/>e passa a operar como <span>receita.</span></h2><p className="muted">A área está preparada para receber cases, indicadores e depoimentos reais. Nenhum resultado fictício é apresentado.</p></Reveal><div className="proof">{[['CASES','Em preparação'],['INDICADORES','Em preparação'],['DEPOIMENTOS','Em preparação']].map(([a,b])=><div key={a}><ChartNoAxesCombined/><b>{a}</b><small>{b}</small></div>)}</div></div></section>}
const qs=['A 7UP é uma agência de tráfego?','Vocês trabalham apenas com marketing?','Vocês implementam CRM?','Vocês trabalham com automação e IA?','Vocês atuam junto ao comercial?','Como funciona o diagnóstico?','Para quais empresas a 7UP é indicada?'];
function FAQ(){const[o,setO]=useState<number|null>(null);return <section className="sec pale"><div className="wrap two"><Reveal><Label n="09" t="Perguntas"/><h2>Menos achismo.<br/><span>Mais clareza.</span></h2></Reveal><div className="faq">{qs.map((q,i)=><div key={q}><button onClick={()=>setO(o===i?null:i)} aria-expanded={o===i}>{q}<ChevronDown className={o===i?'rot':''}/></button>{o===i&&<p>A 7UP conecta marketing, vendas e tecnologia. A resposta depende do estágio e da estrutura atual da empresa, por isso começamos pelo diagnóstico da operação.</p>}</div>)}</div></div></section>}
function CTA(){return <section className="cta" id="contato"><div className="wrap"><Reveal><Logo/><small>10 — PRÓXIMO MOVIMENTO</small><h2>Marketing, vendas e tecnologia<br/><span>não deveriam trabalhar separados.</span></h2><p>Construa uma operação capaz de transformar demanda em receita.</p><Btn>FALAR COM A 7UP</Btn></Reveal></div></section>}
function Footer(){return <footer><div className="wrap foot"><div><Logo/><p>7UP — Engenharia de Receita & Growth.</p></div><div className="flinks">{nav.map(([x,id])=><a key={id} href={'#'+id}>{x}</a>)}</div><small>© {new Date().getFullYear()} 7UP Consultoria em Marketing</small></div></footer>}
function App(){return <><Header/><main><Hero/><Break/><Position/><OS/><Xray/><Process/><Solutions/><Fit/><Proof/><FAQ/><CTA/></main><Footer/><a className="wa" href={WA} target="_blank" rel="noopener noreferrer" aria-label="Falar com a 7UP no WhatsApp"><MessageCircle/></a></>};createRoot(document.getElementById('root')!).render(<App/>);
